"""Hand-authored component catalog + workload tags — per spec.md §4.

Each entry's `workloads` list is curated by hand, not derived by formula at seed
time (spec.md §4.3): every (profile, tier, weight) tuple reflects a judgment call
about that specific part, not a computed threshold. `db/seed.py` is the runner
that loads this data into the database; this module holds only literals.

Socket / ram_type / form_factor strings are shared vocabulary across categories —
keep them consistent (e.g. "AM5" here must match "AM5" on every AM5 motherboard
and every cooler that supports AM5) so engine/compatibility.py string comparisons
work.
"""
from __future__ import annotations

from typing import Any

WorkloadTag = tuple[str, str, float]  # (workload_profile, tier, weight)


def W(profile: str, tier: str, weight: float) -> WorkloadTag:
    return (profile, tier, weight)


def PART(
    category: str,
    name: str,
    brand: str,
    price: float,
    *,
    socket: str | None = None,
    ram_type: str | None = None,
    tdp: int | None = None,
    watt_cap: int | None = None,
    form_factor: str | None = None,
    capacity_gb: int | None = None,
    interface: str | None = None,
    gpu_len: int | None = None,
    cooler_h: int | None = None,
    psu_ff: str | None = None,
    chipset: str | None = None,
    bench: int | None = None,
    specs: dict[str, Any] | None = None,
    workloads: list[WorkloadTag] | None = None,
) -> dict[str, Any]:
    return {
        "category": category,
        "name": name,
        "brand": brand,
        "price_usd": float(price),
        "socket": socket,
        "ram_type": ram_type,
        "tdp_watts": tdp,
        "wattage_capacity": watt_cap,
        "form_factor": form_factor,
        "capacity_gb": capacity_gb,
        "interface": interface,
        "max_gpu_length_mm": gpu_len,
        "max_cooler_height_mm": cooler_h,
        "psu_form_factor_support": psu_ff,
        "chipset": chipset,
        "benchmark_score": bench,
        "specs_json": specs or {},
        "workloads": workloads or [],
    }


# ---------------------------------------------------------------------------
# CPU
# ---------------------------------------------------------------------------
CPUS = [
    PART("CPU", "AMD Ryzen 5 5600", "AMD", 109, socket="AM4", tdp=65, bench=55,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 3.5, "boost_clock_ghz": 4.4},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Entry", 1.0), W("Programming", "Mid", 0.8)]),
    PART("CPU", "AMD Ryzen 5 5600X", "AMD", 139, socket="AM4", tdp=65, bench=58,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 3.7, "boost_clock_ghz": 4.6},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 1.0), W("Programming", "Mid", 0.8)]),
    PART("CPU", "AMD Ryzen 7 5700X", "AMD", 159, socket="AM4", tdp=65, bench=63,
         specs={"core_count": 8, "thread_count": 16, "base_clock_ghz": 3.4, "boost_clock_ghz": 4.6},
         workloads=[W("General", "Mid", 0.9), W("Gaming", "Mid", 0.9), W("Programming", "High", 0.9),
                    W("VideoEditing", "Mid", 0.7)]),
    PART("CPU", "AMD Ryzen 7 5800X3D", "AMD", 229, socket="AM4", tdp=105, bench=72,
         specs={"core_count": 8, "thread_count": 16, "base_clock_ghz": 3.4, "boost_clock_ghz": 4.5},
         workloads=[W("Gaming", "High", 1.0), W("General", "Mid", 0.6), W("Programming", "High", 0.7)]),
    PART("CPU", "AMD Ryzen 5 7600", "AMD", 189, socket="AM5", tdp=65, bench=68,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 3.8, "boost_clock_ghz": 5.1},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 1.0), W("Programming", "Mid", 0.85)]),
    PART("CPU", "AMD Ryzen 5 9600X", "AMD", 219, socket="AM5", tdp=65, bench=70,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 3.9, "boost_clock_ghz": 5.4},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 1.0), W("Programming", "Mid", 0.85)]),
    PART("CPU", "AMD Ryzen 7 7700X", "AMD", 299, socket="AM5", tdp=105, bench=80,
         specs={"core_count": 8, "thread_count": 16, "base_clock_ghz": 4.5, "boost_clock_ghz": 5.4},
         workloads=[W("Gaming", "High", 0.9), W("Programming", "High", 1.0), W("VideoEditing", "High", 0.8),
                    W("General", "Mid", 0.6)]),
    PART("CPU", "AMD Ryzen 7 7800X3D", "AMD", 359, socket="AM5", tdp=120, bench=88,
         specs={"core_count": 8, "thread_count": 16, "base_clock_ghz": 4.2, "boost_clock_ghz": 5.0},
         workloads=[W("Gaming", "High", 1.0), W("Design", "High", 0.6), W("Programming", "High", 0.8)]),
    PART("CPU", "AMD Ryzen 9 7900X", "AMD", 429, socket="AM5", tdp=170, bench=91,
         specs={"core_count": 12, "thread_count": 24, "base_clock_ghz": 4.7, "boost_clock_ghz": 5.6},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "High", 0.9),
                    W("Programming", "Enthusiast", 1.0), W("Gaming", "High", 0.7)]),
    PART("CPU", "AMD Ryzen 9 7950X3D", "AMD", 549, socket="AM5", tdp=120, bench=96,
         specs={"core_count": 16, "thread_count": 32, "base_clock_ghz": 4.2, "boost_clock_ghz": 5.7},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9),
                    W("Design", "Enthusiast", 0.9), W("Programming", "Enthusiast", 1.0)]),
    PART("CPU", "AMD Ryzen 9 9950X", "AMD", 599, socket="AM5", tdp=170, bench=99,
         specs={"core_count": 16, "thread_count": 32, "base_clock_ghz": 4.3, "boost_clock_ghz": 5.7},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Programming", "Enthusiast", 1.0), W("Gaming", "High", 0.8)]),
    PART("CPU", "Intel Core i3-13100F", "Intel", 99, socket="LGA1700", tdp=60, bench=42,
         specs={"core_count": 4, "thread_count": 8, "base_clock_ghz": 3.4, "boost_clock_ghz": 4.5},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.7)]),
    PART("CPU", "Intel Core i5-12400F", "Intel", 129, socket="LGA1700", tdp=65, bench=56,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 2.5, "boost_clock_ghz": 4.4},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Entry", 1.0), W("Programming", "Mid", 0.7)]),
    PART("CPU", "Intel Core i5-13400F", "Intel", 199, socket="LGA1700", tdp=65, bench=62,
         specs={"core_count": 10, "thread_count": 16, "base_clock_ghz": 2.5, "boost_clock_ghz": 4.6},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 1.0), W("Programming", "Mid", 0.8)]),
    PART("CPU", "Intel Core i5-14600K", "Intel", 319, socket="LGA1700", tdp=125, bench=78,
         specs={"core_count": 14, "thread_count": 20, "base_clock_ghz": 3.5, "boost_clock_ghz": 5.3},
         workloads=[W("Gaming", "High", 1.0), W("Programming", "High", 0.9), W("VideoEditing", "Mid", 0.7)]),
    PART("CPU", "Intel Core i7-13700K", "Intel", 409, socket="LGA1700", tdp=125, bench=86,
         specs={"core_count": 16, "thread_count": 24, "base_clock_ghz": 3.4, "boost_clock_ghz": 5.4},
         workloads=[W("Gaming", "High", 0.9), W("VideoEditing", "High", 1.0), W("Design", "High", 0.9),
                    W("Programming", "High", 1.0)]),
    PART("CPU", "Intel Core i7-14700K", "Intel", 419, socket="LGA1700", tdp=125, bench=89,
         specs={"core_count": 20, "thread_count": 28, "base_clock_ghz": 3.4, "boost_clock_ghz": 5.6},
         workloads=[W("VideoEditing", "Enthusiast", 0.9), W("Design", "High", 1.0), W("Gaming", "High", 0.9),
                    W("Programming", "Enthusiast", 0.9)]),
    PART("CPU", "Intel Core i9-14900K", "Intel", 549, socket="LGA1700", tdp=125, bench=97,
         specs={"core_count": 24, "thread_count": 32, "base_clock_ghz": 3.2, "boost_clock_ghz": 6.0},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Gaming", "Enthusiast", 1.0), W("Programming", "Enthusiast", 1.0)]),
    PART("CPU", "Intel Core Ultra 5 245K", "Intel", 309, socket="LGA1851", tdp=125, bench=75,
         specs={"core_count": 14, "thread_count": 14, "base_clock_ghz": 3.6, "boost_clock_ghz": 5.2},
         workloads=[W("Gaming", "High", 0.85), W("Programming", "High", 0.85), W("General", "Mid", 0.5)]),
    PART("CPU", "Intel Core Ultra 9 285K", "Intel", 589, socket="LGA1851", tdp=125, bench=95,
         specs={"core_count": 24, "thread_count": 24, "base_clock_ghz": 3.7, "boost_clock_ghz": 5.7},
         workloads=[W("VideoEditing", "Enthusiast", 0.95), W("Design", "Enthusiast", 0.95),
                    W("Gaming", "High", 0.85), W("Programming", "Enthusiast", 1.0)]),
    PART("CPU", "AMD Ryzen 5 5500", "AMD", 79, socket="AM4", tdp=65, bench=48,
         specs={"core_count": 6, "thread_count": 12, "base_clock_ghz": 3.6, "boost_clock_ghz": 4.2},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.9)]),
    PART("CPU", "Intel Core i3-12100F", "Intel", 89, socket="LGA1700", tdp=58, bench=38,
         specs={"core_count": 4, "thread_count": 8, "base_clock_ghz": 3.3, "boost_clock_ghz": 4.3},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.6)]),
    PART("CPU", "Intel Core i9-14900KS", "Intel", 689, socket="LGA1700", tdp=150, bench=99,
         specs={"core_count": 24, "thread_count": 32, "base_clock_ghz": 3.2, "boost_clock_ghz": 6.2},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Gaming", "Enthusiast", 1.0), W("Programming", "Enthusiast", 1.0)]),
]

# ---------------------------------------------------------------------------
# Motherboard
# ---------------------------------------------------------------------------
MOTHERBOARDS = [
    PART("Motherboard", "MSI B450M PRO-VDH MAX", "MSI", 75, socket="AM4", ram_type="DDR4",
         form_factor="mATX", chipset="B450",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "3.0", "m2_slots": 1, "wifi_onboard": False},
         workloads=[W("General", "Entry", 1.0)]),
    PART("Motherboard", "ASRock B550M-HDV", "ASRock", 80, socket="AM4", ram_type="DDR4",
         form_factor="mATX", chipset="B550",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 1, "wifi_onboard": False},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("Motherboard", "MSI B550-A PRO", "MSI", 110, socket="AM4", ram_type="DDR4",
         form_factor="ATX", chipset="B550",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": False},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Motherboard", "Gigabyte B550 AORUS ELITE", "Gigabyte", 140, socket="AM4", ram_type="DDR4",
         form_factor="ATX", chipset="B550",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": False},
         workloads=[W("Gaming", "Mid", 1.0), W("General", "Mid", 0.7)]),
    PART("Motherboard", "ASUS TUF Gaming X570-Plus", "ASUS", 189, socket="AM4", ram_type="DDR4",
         form_factor="ATX", chipset="X570",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": False},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "Mid", 0.7)]),
    PART("Motherboard", "ASRock B650M-HDV/M.2", "ASRock", 99, socket="AM5", ram_type="DDR5",
         form_factor="mATX", chipset="B650",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 1, "wifi_onboard": False},
         workloads=[W("General", "Mid", 1.0)]),
    PART("Motherboard", "MSI PRO B650M-A", "MSI", 119, socket="AM5", ram_type="DDR5",
         form_factor="mATX", chipset="B650",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": False},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Motherboard", "Gigabyte B650M AORUS PRO", "Gigabyte", 139, socket="AM5", ram_type="DDR5",
         form_factor="mATX", chipset="B650",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": True},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Motherboard", "Gigabyte B650 AORUS ELITE AX", "Gigabyte", 179, socket="AM5", ram_type="DDR5",
         form_factor="ATX", chipset="B650",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": True},
         workloads=[W("Gaming", "Mid", 1.0), W("General", "Mid", 0.6)]),
    PART("Motherboard", "MSI MAG B650 TOMAHAWK", "MSI", 189, socket="AM5", ram_type="DDR5",
         form_factor="ATX", chipset="B650",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 3, "wifi_onboard": False},
         workloads=[W("Gaming", "High", 1.0), W("Programming", "High", 0.6)]),
    PART("Motherboard", "ASUS TUF Gaming X670E-PLUS", "ASUS", 289, socket="AM5", ram_type="DDR5",
         form_factor="ATX", chipset="X670E",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "5.0", "m2_slots": 4, "wifi_onboard": True},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.8), W("Design", "High", 0.8)]),
    PART("Motherboard", "ASUS ROG STRIX X670E-E", "ASUS", 479, socket="AM5", ram_type="DDR5",
         form_factor="ATX", chipset="X670E",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "5.0", "m2_slots": 5, "wifi_onboard": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9),
                    W("Design", "Enthusiast", 0.9)]),
    PART("Motherboard", "ASRock X870 Pro RS", "ASRock", 219, socket="AM5", ram_type="DDR5",
         form_factor="ATX", chipset="X870",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "5.0", "m2_slots": 3, "wifi_onboard": True},
         workloads=[W("Gaming", "High", 1.0), W("Programming", "High", 0.7)]),
    PART("Motherboard", "ASRock B760M-HDV", "ASRock", 89, socket="LGA1700", ram_type="DDR4",
         form_factor="mATX", chipset="B760",
         specs={"ram_slots": 4, "max_ram_gb": 128, "pcie_version": "4.0", "m2_slots": 1, "wifi_onboard": False},
         workloads=[W("General", "Entry", 1.0)]),
    PART("Motherboard", "MSI PRO B760M-A WIFI", "MSI", 129, socket="LGA1700", ram_type="DDR5",
         form_factor="mATX", chipset="B760",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": True},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Motherboard", "ASUS TUF GAMING B760-PLUS WIFI", "ASUS", 169, socket="LGA1700", ram_type="DDR5",
         form_factor="ATX", chipset="B760",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "4.0", "m2_slots": 3, "wifi_onboard": True},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Motherboard", "Gigabyte Z790 AORUS ELITE AX", "Gigabyte", 259, socket="LGA1700", ram_type="DDR5",
         form_factor="ATX", chipset="Z790",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "5.0", "m2_slots": 4, "wifi_onboard": True},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.8)]),
    PART("Motherboard", "MSI MPG Z790 CARBON WIFI", "MSI", 329, socket="LGA1700", ram_type="DDR5",
         form_factor="ATX", chipset="Z790",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "5.0", "m2_slots": 5, "wifi_onboard": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9),
                    W("Design", "Enthusiast", 0.9)]),
    PART("Motherboard", "MSI PRO B860-P WIFI", "MSI", 179, socket="LGA1851", ram_type="DDR5",
         form_factor="ATX", chipset="B860",
         specs={"ram_slots": 4, "max_ram_gb": 192, "pcie_version": "4.0", "m2_slots": 3, "wifi_onboard": True},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Motherboard", "ASUS ROG STRIX Z890-E GAMING WIFI", "ASUS", 499, socket="LGA1851", ram_type="DDR5",
         form_factor="ATX", chipset="Z890",
         specs={"ram_slots": 4, "max_ram_gb": 256, "pcie_version": "5.0", "m2_slots": 5, "wifi_onboard": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9),
                    W("Design", "Enthusiast", 0.9)]),
    PART("Motherboard", "ASRock B650E PG-ITX/WiFi", "ASRock", 239, socket="AM5", ram_type="DDR5",
         form_factor="ITX", chipset="B650E",
         specs={"ram_slots": 2, "max_ram_gb": 96, "pcie_version": "5.0", "m2_slots": 2, "wifi_onboard": True},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("Motherboard", "ASUS ROG Strix B760-I Gaming WiFi", "ASUS", 229, socket="LGA1700", ram_type="DDR5",
         form_factor="ITX", chipset="B760",
         specs={"ram_slots": 2, "max_ram_gb": 96, "pcie_version": "4.0", "m2_slots": 2, "wifi_onboard": True},
         workloads=[W("Gaming", "High", 1.0)]),
]

# ---------------------------------------------------------------------------
# GPU
# ---------------------------------------------------------------------------
GPUS = [
    PART("GPU", "NVIDIA RTX 4060", "NVIDIA", 299, tdp=115, bench=50, interface="PCIe4.0x8",
         specs={"length_mm": 200, "vram_gb": 8, "boost_clock_mhz": 2460},
         workloads=[W("Gaming", "Entry", 1.0), W("General", "Mid", 0.5), W("Programming", "Entry", 0.6)]),
    PART("GPU", "NVIDIA RTX 4060 Ti 16GB", "NVIDIA", 429, tdp=165, bench=58, interface="PCIe4.0x8",
         specs={"length_mm": 220, "vram_gb": 16, "boost_clock_mhz": 2535},
         workloads=[W("Gaming", "Mid", 1.0), W("Design", "Mid", 0.8), W("Programming", "Mid", 0.8)]),
    PART("GPU", "NVIDIA RTX 4070", "NVIDIA", 549, tdp=200, bench=68, interface="PCIe4.0x16",
         specs={"length_mm": 244, "vram_gb": 12, "boost_clock_mhz": 2475},
         workloads=[W("Gaming", "Mid", 1.0), W("VideoEditing", "Mid", 0.8), W("Design", "Mid", 0.8),
                    W("Programming", "Mid", 0.8)]),
    PART("GPU", "NVIDIA RTX 4070 Super", "NVIDIA", 599, tdp=220, bench=74, interface="PCIe4.0x16",
         specs={"length_mm": 267, "vram_gb": 12, "boost_clock_mhz": 2475},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.85), W("Design", "High", 0.8),
                    W("Programming", "High", 0.8)]),
    PART("GPU", "NVIDIA RTX 4070 Ti Super", "NVIDIA", 799, tdp=285, bench=80, interface="PCIe4.0x16",
         specs={"length_mm": 300, "vram_gb": 16, "boost_clock_mhz": 2610},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.9), W("Design", "High", 0.9),
                    W("Programming", "High", 0.85)]),
    PART("GPU", "NVIDIA RTX 4080 Super", "NVIDIA", 999, tdp=320, bench=88, interface="PCIe4.0x16",
         specs={"length_mm": 304, "vram_gb": 16, "boost_clock_mhz": 2550},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.95),
                    W("Design", "Enthusiast", 0.9), W("Programming", "High", 0.8)]),
    PART("GPU", "NVIDIA RTX 4090", "NVIDIA", 1599, tdp=450, bench=100, interface="PCIe4.0x16",
         specs={"length_mm": 336, "vram_gb": 24, "boost_clock_mhz": 2520},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 1.0),
                    W("Design", "Enthusiast", 1.0), W("Programming", "Enthusiast", 1.0)]),
    PART("GPU", "NVIDIA RTX 5070", "NVIDIA", 649, tdp=250, bench=82, interface="PCIe5.0x16",
         specs={"length_mm": 267, "vram_gb": 12, "boost_clock_mhz": 2510},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.85), W("Design", "High", 0.85),
                    W("Programming", "High", 0.8)]),
    PART("GPU", "NVIDIA RTX 5080", "NVIDIA", 999, tdp=360, bench=92, interface="PCIe5.0x16",
         specs={"length_mm": 304, "vram_gb": 16, "boost_clock_mhz": 2620},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.95),
                    W("Design", "Enthusiast", 0.9), W("Programming", "High", 0.85)]),
    PART("GPU", "NVIDIA RTX 5090", "NVIDIA", 1999, tdp=575, bench=100, interface="PCIe5.0x16",
         specs={"length_mm": 336, "vram_gb": 32, "boost_clock_mhz": 2410},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 1.0),
                    W("Design", "Enthusiast", 1.0), W("Programming", "Enthusiast", 1.0)]),
    PART("GPU", "AMD Radeon RX 7600", "AMD", 269, tdp=165, bench=48, interface="PCIe4.0x8",
         specs={"length_mm": 204, "vram_gb": 8, "boost_clock_mhz": 2655},
         workloads=[W("Gaming", "Entry", 1.0), W("General", "Mid", 0.4)]),
    PART("GPU", "AMD Radeon RX 7700 XT", "AMD", 449, tdp=245, bench=65, interface="PCIe4.0x16",
         specs={"length_mm": 267, "vram_gb": 12, "boost_clock_mhz": 2544},
         workloads=[W("Gaming", "Mid", 1.0), W("Design", "Mid", 0.7), W("Programming", "Mid", 0.6)]),
    PART("GPU", "AMD Radeon RX 7800 XT", "AMD", 499, tdp=263, bench=72, interface="PCIe4.0x16",
         specs={"length_mm": 267, "vram_gb": 16, "boost_clock_mhz": 2430},
         workloads=[W("Gaming", "High", 1.0), W("Design", "High", 0.7), W("Programming", "Mid", 0.65)]),
    PART("GPU", "AMD Radeon RX 7900 GRE", "AMD", 549, tdp=260, bench=78, interface="PCIe4.0x16",
         specs={"length_mm": 267, "vram_gb": 16, "boost_clock_mhz": 2245},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "Mid", 0.6), W("Design", "High", 0.7)]),
    PART("GPU", "AMD Radeon RX 7900 XTX", "AMD", 949, tdp=355, bench=90, interface="PCIe4.0x16",
         specs={"length_mm": 287, "vram_gb": 24, "boost_clock_mhz": 2500},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "High", 0.75), W("Design", "High", 0.8)]),
    PART("GPU", "AMD Radeon RX 9070 XT", "AMD", 599, tdp=304, bench=85, interface="PCIe5.0x16",
         specs={"length_mm": 287, "vram_gb": 16, "boost_clock_mhz": 2970},
         workloads=[W("Gaming", "Enthusiast", 0.95), W("Design", "High", 0.75), W("VideoEditing", "High", 0.7)]),
    PART("GPU", "Intel Arc B580", "Intel", 249, tdp=190, bench=52, interface="PCIe4.0x8",
         specs={"length_mm": 187, "vram_gb": 12, "boost_clock_mhz": 2670},
         workloads=[W("Gaming", "Entry", 0.9), W("General", "Mid", 0.4)]),
    PART("GPU", "NVIDIA RTX 3050", "NVIDIA", 219, tdp=130, bench=36, interface="PCIe4.0x8",
         specs={"length_mm": 194, "vram_gb": 8, "boost_clock_mhz": 1777},
         workloads=[W("Gaming", "Entry", 0.85), W("General", "Entry", 0.5)]),
    PART("GPU", "AMD Radeon RX 6600", "AMD", 199, tdp=132, bench=40, interface="PCIe4.0x8",
         specs={"length_mm": 220, "vram_gb": 8, "boost_clock_mhz": 2491},
         workloads=[W("Gaming", "Entry", 0.9), W("General", "Entry", 0.5)]),
    PART("GPU", "Intel Arc A580", "Intel", 179, tdp=185, bench=34, interface="PCIe4.0x8",
         specs={"length_mm": 267, "vram_gb": 8, "boost_clock_mhz": 1700},
         workloads=[W("Gaming", "Entry", 0.75), W("General", "Entry", 0.4)]),
]

# ---------------------------------------------------------------------------
# RAM
# ---------------------------------------------------------------------------
RAM = [
    PART("RAM", "Corsair Vengeance LPX 16GB (2x8GB) DDR4-3200", "Corsair", 39, ram_type="DDR4", capacity_gb=16,
         specs={"module_count": 2, "speed_mhz": 3200, "cas_latency": 16},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("RAM", "Crucial 16GB (2x8GB) DDR4-3200", "Crucial", 36, ram_type="DDR4", capacity_gb=16,
         specs={"module_count": 2, "speed_mhz": 3200, "cas_latency": 22},
         workloads=[W("General", "Entry", 1.0)]),
    PART("RAM", "Corsair Vengeance 8GB (1x8GB) DDR4-3200", "Corsair", 19, ram_type="DDR4", capacity_gb=8,
         specs={"module_count": 1, "speed_mhz": 3200, "cas_latency": 16},
         workloads=[W("General", "Entry", 1.0)]),
    PART("RAM", "Kingston FURY Beast 32GB (2x16GB) DDR4-3200", "Kingston", 74, ram_type="DDR4", capacity_gb=32,
         specs={"module_count": 2, "speed_mhz": 3200, "cas_latency": 16},
         workloads=[W("Gaming", "Mid", 1.0), W("VideoEditing", "Mid", 0.8), W("General", "Mid", 0.6)]),
    PART("RAM", "G.Skill Ripjaws V 64GB (2x32GB) DDR4-3200", "G.Skill", 149, ram_type="DDR4", capacity_gb=64,
         specs={"module_count": 2, "speed_mhz": 3200, "cas_latency": 16},
         workloads=[W("VideoEditing", "High", 1.0), W("Design", "High", 0.9), W("Programming", "High", 0.8)]),
    PART("RAM", "Corsair Vengeance 16GB (2x8GB) DDR5-5600", "Corsair", 54, ram_type="DDR5", capacity_gb=16,
         specs={"module_count": 2, "speed_mhz": 5600, "cas_latency": 36},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("RAM", "Kingston FURY Renegade 16GB (2x8GB) DDR5-6000", "Kingston", 79, ram_type="DDR5", capacity_gb=16,
         specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 32},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("RAM", "TeamGroup T-Force Delta RGB 16GB (2x8GB) DDR5-6000", "TeamGroup", 64, ram_type="DDR5",
         capacity_gb=16, specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 38},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("RAM", "Kingston FURY Beast 32GB (2x16GB) DDR5-5200", "Kingston", 94, ram_type="DDR5", capacity_gb=32,
         specs={"module_count": 2, "speed_mhz": 5200, "cas_latency": 40},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 1.0), W("Programming", "Mid", 0.8)]),
    PART("RAM", "G.Skill Trident Z5 32GB (2x16GB) DDR5-6000", "G.Skill", 109, ram_type="DDR5", capacity_gb=32,
         specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 36},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.85), W("Design", "High", 0.85),
                    W("Programming", "High", 0.85)]),
    PART("RAM", "G.Skill Flare X5 32GB (2x16GB) DDR5-6000", "G.Skill", 114, ram_type="DDR5", capacity_gb=32,
         specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 36},
         workloads=[W("Gaming", "High", 1.0), W("Programming", "High", 0.8)]),
    PART("RAM", "TeamGroup T-Create Expert 32GB (2x16GB) DDR5-6000", "TeamGroup", 104, ram_type="DDR5",
         capacity_gb=32, specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 38},
         workloads=[W("VideoEditing", "High", 1.0), W("Design", "High", 0.9)]),
    PART("RAM", "Corsair Dominator Platinum 32GB (2x16GB) DDR5-6400", "Corsair", 139, ram_type="DDR5",
         capacity_gb=32, specs={"module_count": 2, "speed_mhz": 6400, "cas_latency": 32},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "High", 0.85), W("Design", "High", 0.85)]),
    PART("RAM", "Corsair Vengeance 64GB (2x32GB) DDR5-5600", "Corsair", 189, ram_type="DDR5", capacity_gb=64,
         specs={"module_count": 2, "speed_mhz": 5600, "cas_latency": 40},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Programming", "Enthusiast", 1.0)]),
    PART("RAM", "G.Skill Trident Z5 RGB 64GB (2x32GB) DDR5-6000", "G.Skill", 219, ram_type="DDR5", capacity_gb=64,
         specs={"module_count": 2, "speed_mhz": 6000, "cas_latency": 36},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Programming", "Enthusiast", 1.0), W("Gaming", "Enthusiast", 1.0)]),
    PART("RAM", "Corsair Vengeance 128GB (2x64GB) DDR5-5600", "Corsair", 349, ram_type="DDR5", capacity_gb=128,
         specs={"module_count": 2, "speed_mhz": 5600, "cas_latency": 40},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0),
                    W("Programming", "Enthusiast", 0.9)]),
]

# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------
STORAGE = [
    PART("Storage", "Kingston NV2 500GB", "Kingston", 32, interface="NVMe", capacity_gb=500,
         specs={"read_speed_mbps": 3500, "write_speed_mbps": 2100, "form_factor": "M.2-2280"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("Storage", "Samsung 980 500GB", "Samsung", 39, interface="NVMe", capacity_gb=500,
         specs={"read_speed_mbps": 3500, "write_speed_mbps": 3000, "form_factor": "M.2-2280"},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("Storage", "Samsung 970 EVO Plus 500GB", "Samsung", 44, interface="NVMe", capacity_gb=500,
         specs={"read_speed_mbps": 3500, "write_speed_mbps": 3300, "form_factor": "M.2-2280"},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("Storage", "WD Blue SN580 1TB", "Western Digital", 54, interface="NVMe", capacity_gb=1000,
         specs={"read_speed_mbps": 4150, "write_speed_mbps": 4150, "form_factor": "M.2-2280"},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Storage", "Crucial P3 Plus 1TB", "Crucial", 59, interface="NVMe", capacity_gb=1000,
         specs={"read_speed_mbps": 5000, "write_speed_mbps": 3600, "form_factor": "M.2-2280"},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Mid", 0.8)]),
    PART("Storage", "Kingston KC3000 1TB", "Kingston", 79, interface="NVMe", capacity_gb=1000,
         specs={"read_speed_mbps": 7000, "write_speed_mbps": 6000, "form_factor": "M.2-2280"},
         workloads=[W("Gaming", "High", 1.0), W("Programming", "Mid", 0.7)]),
    PART("Storage", "Crucial P5 Plus 2TB", "Crucial", 119, interface="NVMe", capacity_gb=2000,
         specs={"read_speed_mbps": 6600, "write_speed_mbps": 5000, "form_factor": "M.2-2280"},
         workloads=[W("VideoEditing", "High", 1.0), W("Design", "High", 0.85)]),
    PART("Storage", "Samsung 990 Pro 2TB", "Samsung", 149, interface="NVMe", capacity_gb=2000,
         specs={"read_speed_mbps": 7450, "write_speed_mbps": 6900, "form_factor": "M.2-2280"},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 0.9), W("Gaming", "High", 0.8)]),
    PART("Storage", "WD Black SN850X 2TB", "Western Digital", 159, interface="NVMe", capacity_gb=2000,
         specs={"read_speed_mbps": 7300, "write_speed_mbps": 6600, "form_factor": "M.2-2280"},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Gaming", "High", 0.85)]),
    PART("Storage", "Crucial T700 2TB", "Crucial", 219, interface="NVMe", capacity_gb=2000,
         specs={"read_speed_mbps": 12400, "write_speed_mbps": 11800, "form_factor": "M.2-2280",
                "pcie_generation": "5.0"},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 0.9),
                    W("Programming", "Enthusiast", 0.8)]),
    PART("Storage", "Crucial MX500 1TB", "Crucial", 64, interface="SATA", capacity_gb=1000,
         specs={"read_speed_mbps": 560, "write_speed_mbps": 510, "form_factor": "2.5in"},
         workloads=[W("General", "Mid", 1.0), W("Programming", "Mid", 0.6)]),
    PART("Storage", "WD Blue 1TB SATA SSD", "Western Digital", 54, interface="SATA", capacity_gb=1000,
         specs={"read_speed_mbps": 560, "write_speed_mbps": 530, "form_factor": "2.5in"},
         workloads=[W("General", "Mid", 1.0)]),
    PART("Storage", "Samsung 870 EVO 2TB", "Samsung", 129, interface="SATA", capacity_gb=2000,
         specs={"read_speed_mbps": 560, "write_speed_mbps": 530, "form_factor": "2.5in"},
         workloads=[W("General", "High", 1.0), W("VideoEditing", "Mid", 0.6)]),
    PART("Storage", "Seagate Barracuda 2TB", "Seagate", 54, interface="SATA", capacity_gb=2000,
         specs={"read_speed_mbps": 220, "write_speed_mbps": 220, "form_factor": "3.5in HDD"},
         workloads=[W("General", "Entry", 1.0), W("VideoEditing", "Entry", 0.6)]),
    PART("Storage", "Seagate BarraCuda 4TB", "Seagate", 89, interface="SATA", capacity_gb=4000,
         specs={"read_speed_mbps": 220, "write_speed_mbps": 220, "form_factor": "3.5in HDD"},
         workloads=[W("VideoEditing", "Mid", 0.7), W("Design", "Mid", 0.6)]),
    PART("Storage", "Toshiba X300 6TB", "Toshiba", 139, interface="SATA", capacity_gb=6000,
         specs={"read_speed_mbps": 230, "write_speed_mbps": 230, "form_factor": "3.5in HDD"},
         workloads=[W("VideoEditing", "High", 0.7)]),
]

# ---------------------------------------------------------------------------
# PSU
# ---------------------------------------------------------------------------
PSU = [
    PART("PSU", "EVGA 500 BR", "EVGA", 44, watt_cap=500, form_factor="ATX",
         specs={"efficiency_rating": "80+ Bronze", "modular": False},
         workloads=[W("General", "Entry", 1.0)]),
    PART("PSU", "Thermaltake Smart 500W", "Thermaltake", 39, watt_cap=500, form_factor="ATX",
         specs={"efficiency_rating": "80+ White", "modular": False},
         workloads=[W("General", "Entry", 1.0)]),
    PART("PSU", "Corsair CV550", "Corsair", 54, watt_cap=550, form_factor="ATX",
         specs={"efficiency_rating": "80+ Bronze", "modular": False},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Entry", 0.9)]),
    PART("PSU", "MSI MAG A650BN", "MSI", 64, watt_cap=650, form_factor="ATX",
         specs={"efficiency_rating": "80+ Bronze", "modular": False},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("PSU", "Corsair RM650x", "Corsair", 99, watt_cap=650, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "Mid", 1.0), W("Design", "Mid", 0.8)]),
    PART("PSU", "be quiet! Pure Power 11 700W", "be quiet!", 89, watt_cap=700, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": False},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("PSU", "EVGA SuperNOVA 750 GT", "EVGA", 109, watt_cap=750, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("PSU", "Corsair RM850x", "Corsair", 139, watt_cap=850, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.8)]),
    PART("PSU", "EVGA SuperNOVA 850 GT", "EVGA", 129, watt_cap=850, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "High", 1.0), W("Design", "High", 0.8)]),
    PART("PSU", "Corsair RM1000x", "Corsair", 189, watt_cap=1000, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9)]),
    PART("PSU", "Seasonic Focus GX-1000", "Seasonic", 179, watt_cap=1000, form_factor="ATX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("Design", "Enthusiast", 0.9)]),
    PART("PSU", "Corsair SF600", "Corsair", 109, watt_cap=600, form_factor="SFX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("PSU", "Corsair SF750", "Corsair", 159, watt_cap=750, form_factor="SFX",
         specs={"efficiency_rating": "80+ Platinum", "modular": True},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("PSU", "Silverstone SX700-LPT", "SilverStone", 139, watt_cap=700, form_factor="SFX",
         specs={"efficiency_rating": "80+ Platinum", "modular": True},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("PSU", "Cooler Master V850 SFX Gold", "Cooler Master", 169, watt_cap=850, form_factor="SFX",
         specs={"efficiency_rating": "80+ Gold", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0)]),
    PART("PSU", "Corsair HX1200i", "Corsair", 249, watt_cap=1200, form_factor="ATX",
         specs={"efficiency_rating": "80+ Platinum", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.8)]),
    PART("PSU", "Seasonic Prime TX-1300", "Seasonic", 339, watt_cap=1300, form_factor="ATX",
         specs={"efficiency_rating": "80+ Titanium", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.9)]),
    PART("PSU", "be quiet! Dark Power Pro 13 1500W", "be quiet!", 429, watt_cap=1500, form_factor="ATX",
         specs={"efficiency_rating": "80+ Titanium", "modular": True},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 0.9)]),
    PART("PSU", "Corsair AX1600i", "Corsair", 479, watt_cap=1600, form_factor="ATX",
         specs={"efficiency_rating": "80+ Titanium", "modular": True},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 1.0)]),
]

# ---------------------------------------------------------------------------
# Case
# ---------------------------------------------------------------------------
CASE = [
    PART("Case", "NZXT H510", "NZXT", 79, form_factor="ATX,mATX,ITX", gpu_len=381, cooler_h=165,
         psu_ff="ATX", specs={"fan_mounts": 3, "side_panel_type": "Tempered Glass", "max_radiator_mm": 280},
         workloads=[W("General", "Mid", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("Case", "Corsair 4000D Airflow", "Corsair", 104, form_factor="ATX,mATX,ITX", gpu_len=360, cooler_h=170,
         psu_ff="ATX", specs={"fan_mounts": 6, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Case", "Fractal Design Meshify 2", "Fractal Design", 139, form_factor="ATX,mATX,ITX", gpu_len=470,
         cooler_h=185, psu_ff="ATX",
         specs={"fan_mounts": 9, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.7)]),
    PART("Case", "Lian Li Lancool 215", "Lian Li", 99, form_factor="ATX,mATX,ITX", gpu_len=384, cooler_h=176,
         psu_ff="ATX", specs={"fan_mounts": 5, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Case", "Phanteks P400A", "Phanteks", 89, form_factor="ATX,mATX,ITX", gpu_len=420, cooler_h=160,
         psu_ff="ATX", specs={"fan_mounts": 6, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Case", "Cooler Master MasterBox NR200", "Cooler Master", 99, form_factor="ITX", gpu_len=330,
         cooler_h=155, psu_ff="SFX",
         specs={"fan_mounts": 2, "side_panel_type": "Tempered Glass", "max_radiator_mm": 240},
         workloads=[W("Gaming", "Mid", 0.9)]),
    PART("Case", "NZXT H1 V2", "NZXT", 199, form_factor="ITX", gpu_len=322, cooler_h=92, psu_ff="SFX",
         specs={"fan_mounts": 2, "side_panel_type": "Tempered Glass", "preinstalled_aio_psu": True,
                "max_radiator_mm": 140},
         workloads=[W("Gaming", "High", 0.9)]),
    PART("Case", "Corsair 5000D Airflow", "Corsair", 174, form_factor="ATX,mATX,ITX", gpu_len=420, cooler_h=170,
         psu_ff="ATX", specs={"fan_mounts": 8, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "High", 0.7)]),
    PART("Case", "be quiet! Pure Base 500DX", "be quiet!", 109, form_factor="ATX,mATX,ITX", gpu_len=369,
         cooler_h=190, psu_ff="ATX",
         specs={"fan_mounts": 6, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Mid", 1.0), W("General", "Mid", 0.6)]),
    PART("Case", "Fractal Design Terra", "Fractal Design", 189, form_factor="ITX", gpu_len=336, cooler_h=160,
         psu_ff="SFX", specs={"fan_mounts": 2, "side_panel_type": "Aluminum", "max_radiator_mm": 280},
         workloads=[W("Gaming", "High", 0.9)]),
    PART("Case", "Corsair iCUE 4000X", "Corsair", 134, form_factor="ATX,mATX,ITX", gpu_len=360, cooler_h=170,
         psu_ff="ATX", specs={"fan_mounts": 6, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Case", "Hyte Y40", "Hyte", 149, form_factor="ATX,mATX,ITX", gpu_len=400, cooler_h=160, psu_ff="ATX",
         specs={"fan_mounts": 6, "side_panel_type": "Tempered Glass", "max_radiator_mm": 360},
         workloads=[W("Gaming", "High", 1.0), W("Design", "Mid", 0.6)]),
    PART("Case", "Montech Air 100", "Montech", 60, form_factor="mATX,ITX", gpu_len=320, cooler_h=150,
         psu_ff="ATX", specs={"fan_mounts": 3, "side_panel_type": "Mesh", "max_radiator_mm": 240},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.8)]),
    PART("Case", "Lian Li A4-H2O", "Lian Li", 149, form_factor="ITX", gpu_len=322, cooler_h=45, psu_ff="SFX",
         specs={"fan_mounts": 1, "side_panel_type": "Aluminum", "air_cooler_supported": False,
                "max_radiator_mm": 240},
         workloads=[W("Gaming", "High", 0.8)]),
    PART("Case", "Fractal Design Define 7", "Fractal Design", 169, form_factor="ATX,mATX,ITX", gpu_len=440,
         cooler_h=185, psu_ff="ATX",
         specs={"fan_mounts": 9, "side_panel_type": "Solid/Glass", "max_radiator_mm": 420},
         workloads=[W("VideoEditing", "Enthusiast", 1.0), W("Design", "Enthusiast", 1.0), W("General", "High", 0.6)]),
]

# ---------------------------------------------------------------------------
# Cooler
# ---------------------------------------------------------------------------
COOLER = [
    PART("Cooler", "Cooler Master Hyper 212", "Cooler Master", 35, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 159, "noise_level_dba": 26},
         workloads=[W("General", "Entry", 1.0), W("Gaming", "Entry", 0.9)]),
    PART("Cooler", "DeepCool AK400", "DeepCool", 39, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 155, "noise_level_dba": 28},
         workloads=[W("Gaming", "Entry", 1.0)]),
    PART("Cooler", "ID-COOLING SE-224-XT", "ID-COOLING", 30, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 154, "noise_level_dba": 27},
         workloads=[W("General", "Entry", 1.0)]),
    PART("Cooler", "Thermalright Peerless Assassin 120 SE", "Thermalright", 35,
         socket="AM4,AM5,LGA1700,LGA1200,LGA1851",
         specs={"cooler_type": "Air", "height_mm": 155, "noise_level_dba": 25},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Cooler", "Noctua NH-U12S Redux", "Noctua", 55, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 158, "noise_level_dba": 22.4},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Cooler", "Noctua NH-D15", "Noctua", 109, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 165, "noise_level_dba": 24.6},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.7)]),
    PART("Cooler", "be quiet! Dark Rock Pro 4", "be quiet!", 89, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "Air", "height_mm": 163, "noise_level_dba": 24.3},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("Cooler", "Noctua NH-L9a-AM5", "Noctua", 55, socket="AM5",
         specs={"cooler_type": "Air", "height_mm": 37, "low_profile": True, "noise_level_dba": 23.6},
         workloads=[W("Gaming", "Mid", 0.7)]),
    PART("Cooler", "Cooler Master MasterLiquid ML240L", "Cooler Master", 74,
         socket="AM4,AM5,LGA1700,LGA1200", specs={"cooler_type": "AIO", "radiator_size_mm": 240},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("Cooler", "NZXT Kraken 240", "NZXT", 139, socket="AM4,AM5,LGA1700,LGA1200,LGA1851",
         specs={"cooler_type": "AIO", "radiator_size_mm": 240},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("Cooler", "Corsair iCUE H100i Elite", "Corsair", 139, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "AIO", "radiator_size_mm": 240},
         workloads=[W("Gaming", "High", 1.0)]),
    PART("Cooler", "NZXT Kraken 280", "NZXT", 159, socket="AM4,AM5,LGA1700",
         specs={"cooler_type": "AIO", "radiator_size_mm": 280},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.7)]),
    PART("Cooler", "Arctic Liquid Freezer II 280", "Arctic", 119, socket="AM4,AM5,LGA1700,LGA1200,LGA1851",
         specs={"cooler_type": "AIO", "radiator_size_mm": 280},
         workloads=[W("Gaming", "High", 1.0), W("VideoEditing", "High", 0.7)]),
    PART("Cooler", "Corsair iCUE H150i Elite", "Corsair", 189, socket="AM4,AM5,LGA1700,LGA1200",
         specs={"cooler_type": "AIO", "radiator_size_mm": 360},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.8)]),
    PART("Cooler", "Lian Li Galahad II 360", "Lian Li", 140, socket="AM4,AM5,LGA1700,LGA1200,LGA1851",
         specs={"cooler_type": "AIO", "radiator_size_mm": 360},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("Design", "High", 0.6)]),
    PART("Cooler", "NZXT Kraken 420", "NZXT", 219, socket="AM4,AM5,LGA1700,LGA1200,LGA1851",
         specs={"cooler_type": "AIO", "radiator_size_mm": 420},
         workloads=[W("Gaming", "Enthusiast", 1.0), W("VideoEditing", "Enthusiast", 0.85),
                    W("Design", "Enthusiast", 0.8)]),
]

# ---------------------------------------------------------------------------
# Peripherals
# ---------------------------------------------------------------------------
PERIPHERALS = [
    PART("NetworkCard", "TP-Link Archer TX3000E", "TP-Link", 40,
         specs={"interface_speed": "2.4Gbps", "wifi_standard": "WiFi 6"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("NetworkCard", "ASUS PCE-AX58BT", "ASUS", 45,
         specs={"interface_speed": "2.4Gbps", "wifi_standard": "WiFi 6"},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("NetworkCard", "Intel AX210 PCIe WiFi 6E", "Intel", 35,
         specs={"interface_speed": "2.4Gbps", "wifi_standard": "WiFi 6E"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("SoundCard", "Creative Sound Blaster Z", "Creative", 80,
         specs={"channels": "5.1", "dac_quality": "116dB SNR"},
         workloads=[W("Gaming", "Mid", 1.0)]),
    PART("SoundCard", "ASUS Xonar SE", "ASUS", 30,
         specs={"channels": "5.1", "dac_quality": "116dB SNR"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("OpticalDrive", "LG WH16NS40", "LG", 55,
         specs={"disc_types_supported": "Blu-ray/DVD/CD writer"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("OpticalDrive", "ASUS DRW-24D5MT", "ASUS", 20,
         specs={"disc_types_supported": "DVD/CD writer"},
         workloads=[W("General", "Entry", 1.0)]),
    PART("OpticalDrive", "Pioneer BDR-XD05B", "Pioneer", 89,
         specs={"disc_types_supported": "Blu-ray/DVD/CD writer", "external": True},
         workloads=[W("General", "Mid", 1.0)]),
]

ALL_COMPONENTS: list[dict[str, Any]] = [
    *CPUS,
    *MOTHERBOARDS,
    *GPUS,
    *RAM,
    *STORAGE,
    *PSU,
    *CASE,
    *COOLER,
    *PERIPHERALS,
]
