"""Mass content reset & seeder — a strictly data-only operator script (see
this repo's root CLAUDE.md guardrail: no application/engine/UI/theme/config
code is touched by this file's existence or by running it).

Performs a hard wipe of the three dynamic content tables (`builds`,
`community_posts`, `community_comments` — cascades to `build_components` and
comment replies via the real FK `ondelete="CASCADE"` constraints, enabled at
the connection level by db/database.py's `_enable_sqlite_foreign_keys`) while
leaving every `users` row (including the standing "admin" login and the 5
persona accounts from db/seed_demo.py) completely untouched, then reseeds:

- 70 total builds: 15 owned by admin (5 Budget-mode at 5 distinct ceilings,
  5 Workload-mode at 5 distinct profile/tier combos, 5 Free-mode "freestyle"
  builds), 55 distributed 11-each across the 5 persona users.
- Exactly 30 of those 70 published to the community feed (8 of admin's 15,
  22 of the 55 persona builds), flair balanced ~15/~15 between "Rate My
  Build" and "Looking for Help", each with a distinct, data-derived
  author_notes string.
- 2-5 comments (a mix of root-level and nested replies via
  `parent_comment_id`) on every one of those 30 published posts, authored by
  a realistic mix of the 6 existing users.

Every generated build is verified compatible (`engine.compatibility.
evaluate_build(...).is_compatible`) before it is ever persisted — Free-mode
builds are generated by walking `engine.solvers.CATEGORY_ORDER`/
`PERIPHERAL_CATEGORIES` and, at each step, choosing only from
`solvers.get_compatible_candidates(...)` (itself a full-build re-check, not
just a pairwise one), the same guarantee `db/seed_admin_builds.py`'s own
hand-picked Free-mode plans rely on `evaluate_build` for. Budget/Workload
builds reuse `engine.solvers.initialize_budget_build`/
`allocate_workload_baseline` directly, which already guarantee compatibility
by construction. No score is ever computed via `llm/` — same
network-independent, `db/seed_admin_builds.py`-established convention.

Run directly: `python -m db.seed_mass_content`
"""
from __future__ import annotations

import random
from dataclasses import dataclass

from sqlalchemy import delete

from db.database import init_db, session_scope
from db.models import Build, BuildComponent, CommunityComment, CommunityPost
from db.repositories import builds_repo, community_repo, users_repo
from db.seed import run_seed as run_catalog_seed
from db.seed_demo import DEMO_USERNAMES
from engine import scoring, solvers
from engine.compatibility import BuildState, evaluate_build

_SEED = 20260926  # deterministic across reruns of this one-shot reset script


@dataclass
class BuildPlan:
    name: str
    creation_mode: str  # "Budget" | "Workload" | "Free"
    workload_profile: str | None = None
    tier: str | None = None
    budget_ceiling: float | None = None


def _generate_build_state(plan: BuildPlan, rng: random.Random) -> BuildState:
    if plan.creation_mode == "Budget":
        return solvers.initialize_budget_build(plan.budget_ceiling, fill_peripherals_with_surplus=True)
    if plan.creation_mode == "Workload":
        return solvers.allocate_workload_baseline(
            plan.workload_profile, target_tier=plan.tier, include_peripherals=True
        )
    return _generate_free_build(rng)


def _generate_free_build(rng: random.Random) -> BuildState:
    """Mode C freestyle: walk every category, at each step picking a random
    candidate from `get_compatible_candidates` — which re-checks the WHOLE
    hypothetical build via `evaluate_build`, not just the new part against
    one neighbor — so the final build_state is guaranteed fully compatible
    by construction, the same guarantee every other creation mode has."""
    build_state: BuildState = {}
    for category in solvers.CATEGORY_ORDER:
        candidates = solvers.get_compatible_candidates(category, build_state)
        if candidates:
            build_state[category] = rng.choice(candidates)
    for category in solvers.PERIPHERAL_CATEGORIES:
        if rng.random() < 0.7:
            candidates = solvers.get_compatible_candidates(category, build_state)
            if candidates:
                build_state[category] = rng.choice(candidates)
    return build_state


def _build_total_cost(build_state: BuildState) -> float:
    return sum(component.price_usd for component in build_state.values())


def _create_build(plan: BuildPlan, user_id: int, rng: random.Random) -> tuple[Build, BuildState] | None:
    build_state = _generate_build_state(plan, rng)
    report = evaluate_build(build_state)
    if not report.is_compatible:
        print(f"  WARNING: '{plan.name}' has compatibility issues, NOT persisting: {report.issues}")
        return None
    total_cost = _build_total_cost(build_state)
    bottleneck_pct, _direction = scoring.bottleneck_percentage_baseline(build_state)
    synergy_score = scoring.heuristic_synergy_score(report.compatibility_score, bottleneck_pct)
    components = [
        builds_repo.BuildComponentInput(component_id=component.id, quantity=1)
        for component in build_state.values()
    ]
    build = builds_repo.create_build(
        user_id=user_id,
        name=plan.name,
        creation_mode=plan.creation_mode,
        components=components,
        total_cost=total_cost,
        compatibility_score=report.compatibility_score,
        workload_profile=plan.workload_profile,
        workload_tier=plan.tier,
        budget_ceiling=plan.budget_ceiling,
        synergy_score=synergy_score,
        bottleneck_percentage=bottleneck_pct,
        is_public=False,
    )
    return build, build_state


# ---------------------------------------------------------------------------
# Build plans
# ---------------------------------------------------------------------------

ADMIN_PLANS: list[BuildPlan] = [
    # 5x Budget-capped
    BuildPlan("Admin Budget Build - $1,200 Ceiling", "Budget", budget_ceiling=1200.0),
    BuildPlan("Admin Budget Build - $2,500 Ceiling", "Budget", budget_ceiling=2500.0),
    BuildPlan("Admin Budget Build - $4,000 Ceiling", "Budget", budget_ceiling=4000.0),
    BuildPlan("Admin Budget Build - $5,500 Ceiling", "Budget", budget_ceiling=5500.0),
    BuildPlan("Admin Budget Build - $6,000 Ceiling", "Budget", budget_ceiling=6000.0),
    # 5x Workload/Type
    BuildPlan("Admin Workload Build - Pure Esports Gaming", "Workload", workload_profile="Gaming", tier="Enthusiast"),
    BuildPlan(
        "Admin Workload Build - 4K Video Editing & Content Creation",
        "Workload", workload_profile="VideoEditing", tier="High",
    ),
    BuildPlan("Admin Workload Build - Office & Productivity", "Workload", workload_profile="General", tier="Entry"),
    BuildPlan("Admin Workload Build - Silent Workstation", "Workload", workload_profile="Design", tier="Mid"),
    BuildPlan(
        "Admin Workload Build - AI & ML Research Rig",
        "Workload", workload_profile="Programming", tier="Enthusiast",
    ),
    # 5x Freestyle
    BuildPlan("Admin Freestyle Build - Extreme Top-Tier Showcase", "Free"),
    BuildPlan("Admin Freestyle Build - Glass-Panel RGB Experiment", "Free"),
    BuildPlan("Admin Freestyle Build - Weekend Wildcard", "Free"),
    BuildPlan("Admin Freestyle Build - Creator's Sandbox Rig", "Free"),
    BuildPlan("Admin Freestyle Build - No-Rules Enthusiast Build", "Free"),
]

_PERSONA_PLANS: dict[str, list[BuildPlan]] = {
    "tech_enthusiast": [
        BuildPlan("Tech Enthusiast Budget Build - $1,800 Ceiling", "Budget", budget_ceiling=1800.0),
        BuildPlan("Tech Enthusiast Budget Build - $3,200 Ceiling", "Budget", budget_ceiling=3200.0),
        BuildPlan("Tech Enthusiast Budget Build - $4,800 Ceiling", "Budget", budget_ceiling=4800.0),
        BuildPlan("Tech Enthusiast Budget Build - $7,000 Ceiling", "Budget", budget_ceiling=7000.0),
        BuildPlan("Tech Enthusiast Workload Build - Gaming (Mid)", "Workload", workload_profile="Gaming", tier="Mid"),
        BuildPlan(
            "Tech Enthusiast Workload Build - Video Editing (High)",
            "Workload", workload_profile="VideoEditing", tier="High",
        ),
        BuildPlan(
            "Tech Enthusiast Workload Build - Design (Entry)",
            "Workload", workload_profile="Design", tier="Entry",
        ),
        BuildPlan(
            "Tech Enthusiast Workload Build - Programming (Enthusiast)",
            "Workload", workload_profile="Programming", tier="Enthusiast",
        ),
        BuildPlan("Tech Enthusiast Freestyle - Weekend Experiment #1", "Free"),
        BuildPlan("Tech Enthusiast Freestyle - Weekend Experiment #2", "Free"),
        BuildPlan("Tech Enthusiast Freestyle - Weekend Experiment #3", "Free"),
    ],
    "budget_gamer": [
        BuildPlan("Budget Gamer Build - $700 Ceiling", "Budget", budget_ceiling=700.0),
        BuildPlan("Budget Gamer Build - $1,000 Ceiling", "Budget", budget_ceiling=1000.0),
        BuildPlan("Budget Gamer Build - $1,400 Ceiling", "Budget", budget_ceiling=1400.0),
        BuildPlan("Budget Gamer Build - $1,900 Ceiling", "Budget", budget_ceiling=1900.0),
        BuildPlan("Budget Gamer Workload - Gaming (Entry)", "Workload", workload_profile="Gaming", tier="Entry"),
        BuildPlan("Budget Gamer Workload - Gaming (Mid)", "Workload", workload_profile="Gaming", tier="Mid"),
        BuildPlan("Budget Gamer Workload - Gaming (High)", "Workload", workload_profile="Gaming", tier="High"),
        BuildPlan("Budget Gamer Workload - General (Entry)", "Workload", workload_profile="General", tier="Entry"),
        BuildPlan("Budget Gamer Freestyle - Bargain Bin Build #1", "Free"),
        BuildPlan("Budget Gamer Freestyle - Bargain Bin Build #2", "Free"),
        BuildPlan("Budget Gamer Freestyle - Bargain Bin Build #3", "Free"),
    ],
    "ai_researcher": [
        BuildPlan("AI Researcher Budget Build - $3,500 Ceiling", "Budget", budget_ceiling=3500.0),
        BuildPlan("AI Researcher Budget Build - $5,000 Ceiling", "Budget", budget_ceiling=5000.0),
        BuildPlan("AI Researcher Budget Build - $6,500 Ceiling", "Budget", budget_ceiling=6500.0),
        BuildPlan("AI Researcher Budget Build - $8,000 Ceiling", "Budget", budget_ceiling=8000.0),
        BuildPlan(
            "AI Researcher Workload - Programming (High)",
            "Workload", workload_profile="Programming", tier="High",
        ),
        BuildPlan(
            "AI Researcher Workload - Programming (Enthusiast)",
            "Workload", workload_profile="Programming", tier="Enthusiast",
        ),
        BuildPlan(
            "AI Researcher Workload - VideoEditing (High)",
            "Workload", workload_profile="VideoEditing", tier="High",
        ),
        BuildPlan("AI Researcher Workload - Design (Mid)", "Workload", workload_profile="Design", tier="Mid"),
        BuildPlan("AI Researcher Freestyle - Multi-GPU Training Rig", "Free"),
        BuildPlan("AI Researcher Freestyle - Dataset Crunching Build", "Free"),
        BuildPlan("AI Researcher Freestyle - Lab Spare Node", "Free"),
    ],
    "cad_pro": [
        BuildPlan("CAD Pro Budget Build - $2,800 Ceiling", "Budget", budget_ceiling=2800.0),
        BuildPlan("CAD Pro Budget Build - $4,200 Ceiling", "Budget", budget_ceiling=4200.0),
        BuildPlan("CAD Pro Budget Build - $5,800 Ceiling", "Budget", budget_ceiling=5800.0),
        BuildPlan("CAD Pro Budget Build - $7,200 Ceiling", "Budget", budget_ceiling=7200.0),
        BuildPlan("CAD Pro Workload - Design (Mid)", "Workload", workload_profile="Design", tier="Mid"),
        BuildPlan("CAD Pro Workload - Design (High)", "Workload", workload_profile="Design", tier="High"),
        BuildPlan("CAD Pro Workload - Design (Enthusiast)", "Workload", workload_profile="Design", tier="Enthusiast"),
        BuildPlan(
            "CAD Pro Workload - VideoEditing (Mid)",
            "Workload", workload_profile="VideoEditing", tier="Mid",
        ),
        BuildPlan("CAD Pro Freestyle - Render Farm Node #1", "Free"),
        BuildPlan("CAD Pro Freestyle - Render Farm Node #2", "Free"),
        BuildPlan("CAD Pro Freestyle - Studio Workstation", "Free"),
    ],
    "silent_builder": [
        BuildPlan("Silent Builder Budget Build - $1,500 Ceiling", "Budget", budget_ceiling=1500.0),
        BuildPlan("Silent Builder Budget Build - $2,200 Ceiling", "Budget", budget_ceiling=2200.0),
        BuildPlan("Silent Builder Budget Build - $3,000 Ceiling", "Budget", budget_ceiling=3000.0),
        BuildPlan("Silent Builder Budget Build - $4,500 Ceiling", "Budget", budget_ceiling=4500.0),
        BuildPlan("Silent Builder Workload - General (Mid)", "Workload", workload_profile="General", tier="Mid"),
        BuildPlan("Silent Builder Workload - General (High)", "Workload", workload_profile="General", tier="High"),
        BuildPlan("Silent Builder Workload - Design (Entry)", "Workload", workload_profile="Design", tier="Entry"),
        BuildPlan(
            "Silent Builder Workload - Programming (Mid)",
            "Workload", workload_profile="Programming", tier="Mid",
        ),
        BuildPlan("Silent Builder Freestyle - Quiet Living Room Build", "Free"),
        BuildPlan("Silent Builder Freestyle - Low-Noise Office Rig", "Free"),
        BuildPlan("Silent Builder Freestyle - Whisper-Quiet Media PC", "Free"),
    ],
}

# Which of admin's 15 (index into ADMIN_PLANS, creation order) get published —
# 2 Budget + 3 Workload + 3 Free = 8, spanning every creation mode.
_ADMIN_PUBLISH_INDICES = (0, 1, 5, 6, 7, 10, 11, 12)

# How many of each persona's 11 builds get published (5+5+4+4+4 = 22) —
# always the first N in that persona's own list (a Budget/Workload/Free mix
# by construction, since each persona list is itself ordered that way).
_PERSONA_PUBLISH_COUNTS: dict[str, int] = {
    "tech_enthusiast": 5,
    "budget_gamer": 5,
    "ai_researcher": 4,
    "cad_pro": 4,
    "silent_builder": 4,
}

FLAIR_RATE = "Rate My Build"
FLAIR_HELP = "Looking for Help"

_RATE_TITLE_TEMPLATES = [
    "{cpu} + {gpu} — how'd I do?",
    "Rate my {profile_word}build: {cpu} / {gpu}",
    "First real build, {cpu} + {gpu} — brutal honesty welcome",
    "{gpu} paired with {cpu}, ${total:,.0f} all in",
]
_HELP_TITLE_TEMPLATES = [
    "Need advice: {cpu} / {gpu} — did I mess this up?",
    "Is {gpu} overkill for this {cpu}?",
    "Sanity check before I pull the trigger: {cpu} + {gpu}",
    "Stuck between parts — currently at {cpu} / {gpu}, ${total:,.0f}",
]

_RATE_NOTE_TEMPLATES = [
    "Landed on the {cpu} with a {gpu} for about ${total:,.0f}. Wanted something "
    "that wouldn't bottleneck at 1440p — figured I'd share before I pull the trigger.",
    "This is my take on a {profile_word}rig. {gpu} felt like the sweet spot for the "
    "money, and the {cpu} keeps it fed. Curious what this community thinks of the "
    "PSU headroom on this one.",
    "Went a little all-in on the {gpu} here and backfilled the rest around it. "
    "Total came out to ${total:,.0f} — tell me if that cooler is going to struggle "
    "under load.",
    "Tried to keep this one balanced rather than GPU-heavy — {cpu} and {gpu} "
    "should trade blows fairly evenly. Open to trade-off suggestions on the RAM kit.",
    "Aesthetic was half the goal on this build, performance the other half. "
    "{gpu} clears the case with room to spare. Anyone see an obvious weak link?",
    "Benchmarked this in my head before committing to the {gpu} — {cpu} should "
    "keep up for the workloads I care about. Would love a second opinion on synergy.",
    "First time going with this combo ({cpu} / {gpu}). ${total:,.0f} total, and "
    "I'd rather hear the criticism now than after the order ships.",
    "Wanted a build that photographs as good as it benches. {gpu} was the anchor "
    "part, everything else got picked to not choke it. Thoughts on thermals?",
]
_HELP_NOTE_TEMPLATES = [
    "Torn between sticking with this {cpu} or bumping up a tier — {gpu} is "
    "already locked in. Is ${total:,.0f} total reasonable for what I'm getting?",
    "Not sure the PSU on this one has enough headroom under the {gpu} at full "
    "load. Anyone run the numbers on a similar {cpu} pairing?",
    "First build ever, so please be blunt: does the {cpu} bottleneck this {gpu} "
    "in anything demanding, or am I overthinking it?",
    "Trying to decide if the cooler I picked can actually handle the {cpu} under "
    "sustained load, or if I need to size up before this ships.",
    "Budget's basically maxed at ${total:,.0f} with this {gpu} — is there a "
    "smarter allocation I'm missing before I lock the {cpu} in?",
    "Aesthetic-wise I like where this landed, but I genuinely don't know if the "
    "{gpu} clearance is going to be a problem in this case. Anyone dealt with this?",
    "Would a different RAM kit meaningfully help the {cpu}/{gpu} combo here, or "
    "is it a marginal upgrade not worth the extra spend?",
    "Benchmarks I've seen online don't quite agree on how this {gpu} performs "
    "with a {cpu} — anyone actually run this pairing themselves?",
]

_ROOT_COMMENT_TEMPLATES = [
    "That {gpu} is going to fly with the {cpu} — solid pairing.",
    "How's the PSU headroom looking under full load? That {gpu} pulls a lot.",
    "Really like the aesthetic match on this one, the color scheme is clean.",
    "Curious what benchmarks you're seeing with the {cpu} in anything CPU-bound.",
    "Would've gone one tier down on the {gpu} and put the difference into storage, but this works too.",
    "Thermals on the {cpu} should be fine as long as the case has decent airflow.",
    "${total:,.0f} for this spec is honestly a great price right now.",
    "The RAM kit might be the one thing I'd reconsider here — everything else looks tight.",
    "Nice trade-off picking the {cpu} instead of going a tier higher, saves real money.",
    "This is basically the build I'm eyeing too, good to see someone else land on it.",
    "Cooler choice looks right for that socket, shouldn't have any clearance issues.",
    "Been running something close to this for months, zero regrets on the {gpu}.",
]
_REPLY_COMMENT_TEMPLATES = [
    "Agreed — I checked the wattage math myself and it clears with room to spare.",
    "Yeah that was my thinking too, the {cpu} doesn't need anything fancier here.",
    "Good catch, I'd double check that before finalizing though.",
    "Can confirm, I've had good thermals with a similar setup.",
    "Worth asking in the compatibility thread too, but this looks fine to me.",
    "That's fair — the case airflow really is the deciding factor there.",
    "From admin's side, this checks out against our own compatibility pass too.",
    "Same conclusion I reached benchmarking a near-identical config.",
    "Honestly the {gpu} carries this build, rest is just supporting cast.",
    "Solid point — I'd only swap that if budget allows a bit more headroom.",
]


def _fmt_names(build_state: BuildState) -> dict[str, str]:
    cpu = build_state.get("CPU")
    gpu = build_state.get("GPU")
    return {
        "cpu": cpu.name if cpu else "an unnamed CPU",
        "gpu": gpu.name if gpu else "an unnamed GPU",
    }


def _profile_word(build: Build) -> str:
    return f"{build.workload_profile.lower()} " if build.workload_profile else ""


def _publish(build: Build, build_state: BuildState, flair: str, rng: random.Random) -> int:
    names = _fmt_names(build_state)
    title_pool = _RATE_TITLE_TEMPLATES if flair == FLAIR_RATE else _HELP_TITLE_TEMPLATES
    note_pool = _RATE_NOTE_TEMPLATES if flair == FLAIR_RATE else _HELP_NOTE_TEMPLATES
    title = rng.choice(title_pool).format(
        cpu=names["cpu"], gpu=names["gpu"], total=build.total_cost, profile_word=_profile_word(build)
    )
    notes = rng.choice(note_pool).format(
        cpu=names["cpu"], gpu=names["gpu"], total=build.total_cost, profile_word=_profile_word(build)
    )
    builds_repo.set_public(build.id, True)
    post = community_repo.create_post(build_id=build.id, user_id=build.user_id, title=title, author_notes=notes, flair=flair)
    return post.id


def _add_comments(
    post_id: int, build_state: BuildState, total_cost: float, user_ids: list[int], rng: random.Random
) -> None:
    names = _fmt_names(build_state)
    comment_count = rng.randint(2, 5)
    posted_ids: list[int] = []
    for _ in range(comment_count):
        author_id = rng.choice(user_ids)
        parent_id = None
        if posted_ids and rng.random() < 0.5:
            parent_id = rng.choice(posted_ids)
        pool = _REPLY_COMMENT_TEMPLATES if parent_id is not None else _ROOT_COMMENT_TEMPLATES
        content = rng.choice(pool).format(cpu=names["cpu"], gpu=names["gpu"], total=total_cost)
        comment = community_repo.add_comment(
            post_id=post_id, user_id=author_id, content=content, parent_comment_id=parent_id
        )
        posted_ids.append(comment.id)


def _wipe_dynamic_content() -> None:
    with session_scope() as session:
        session.execute(delete(CommunityComment))
        session.execute(delete(CommunityPost))
        session.execute(delete(BuildComponent))
        session.execute(delete(Build))


def run_mass_content_seed() -> dict:
    init_db()
    run_catalog_seed()  # idempotent; ensures catalog components exist to reference

    admin = users_repo.get_by_username("admin")
    if admin is None:
        raise RuntimeError(
            "admin user not found — run `python -m db.seed_demo` first to establish "
            "the standing admin login and 5 persona users this script reseeds content for."
        )
    persona_users = {username: users_repo.get_by_username(username) for username in DEMO_USERNAMES}
    missing = [username for username, user in persona_users.items() if user is None]
    if missing:
        raise RuntimeError(f"persona users not found: {missing} — run `python -m db.seed_demo` first.")

    _wipe_dynamic_content()

    rng = random.Random(_SEED)
    all_user_ids = [admin.id] + [user.id for user in persona_users.values()]

    admin_builds: list[tuple[Build, BuildState]] = []
    for plan in ADMIN_PLANS:
        result = _create_build(plan, admin.id, rng)
        if result is not None:
            admin_builds.append(result)

    persona_builds: dict[str, list[tuple[Build, BuildState]]] = {}
    for username, user in persona_users.items():
        built: list[tuple[Build, BuildState]] = []
        for plan in _PERSONA_PLANS[username]:
            result = _create_build(plan, user.id, rng)
            if result is not None:
                built.append(result)
        persona_builds[username] = built

    published_count = 0
    for index in _ADMIN_PUBLISH_INDICES:
        if index >= len(admin_builds):
            continue
        build, build_state = admin_builds[index]
        flair = FLAIR_RATE if published_count % 2 == 0 else FLAIR_HELP
        post_id = _publish(build, build_state, flair, rng)
        _add_comments(post_id, build_state, build.total_cost, all_user_ids, rng)
        published_count += 1

    for username, built in persona_builds.items():
        publish_n = _PERSONA_PUBLISH_COUNTS[username]
        for build, build_state in built[:publish_n]:
            flair = FLAIR_RATE if published_count % 2 == 0 else FLAIR_HELP
            post_id = _publish(build, build_state, flair, rng)
            _add_comments(post_id, build_state, build.total_cost, all_user_ids, rng)
            published_count += 1

    total_builds = len(admin_builds) + sum(len(v) for v in persona_builds.values())
    return {
        "total_builds": total_builds,
        "admin_builds": len(admin_builds),
        "persona_builds": {k: len(v) for k, v in persona_builds.items()},
        "published": published_count,
    }


if __name__ == "__main__":
    summary = run_mass_content_seed()
    print(f"Seeded {summary['total_builds']} builds ({summary['admin_builds']} admin).")
    print(f"Published {summary['published']} posts with threaded comments.")
    print(f"Persona build counts: {summary['persona_builds']}")
